### ISSUE TITLE
Diff fails with TypeError: Cannot read properties of undefined (reading 'missing')

### ISSUE THREAD

**Issue by sonicflare** [joshweir/cdk-pretty-diff#5]
```
import { writeFileSync } from "fs";
import { getCustomDiff, renderCustomDiffToHtmlString } from "cdk-pretty-diff";

getCustomDiff().then((nicerDiffs) => {
  const html = renderCustomDiffToHtmlString(nicerDiffs, "CDK Diff");
  writeFileSync("diff.html", html);
});

```
```
$ npx ts-node pretty-diff.ts 
loading configuration
loading sdk provider
initializing CloudFormationDeployments
initializing CloudExecutable
loading plugins
initializing CustomCdkToolkit
initializing CustomCdkToolkit super class
selectStacksForDiff
infra/node_modules/aws-cdk/lib/api/cxapp/cloud-executable.ts:81
      if (assembly.manifest.missing && assembly.manifest.missing.length > 0) {
                            ^
TypeError: Cannot read properties of undefined (reading 'missing')
    at CloudExecutable.doSynthesize (infra/node_modules/aws-cdk/lib/api/cxapp/cloud-executable.ts:81:29)
    at async CloudExecutable.synthesize (infra/node_modules/aws-cdk/lib/api/cxapp/cloud-executable.ts:65:29)
    at async CustomCdkToolkit.selectStacksForDiff (infra/node_modules/aws-cdk/lib/cdk-toolkit.ts:686:22)
    at async CustomCdkToolkit.getDiffObject (infra/node_modules/cdk-pretty-diff/src/cdk-reverse-engineered.ts:126:20)
    at async Object.exports.getCustomDiff (infra/node_modules/cdk-pretty-diff/src/custom-diff.ts:6:31)

```
CDK version 2.62.0
cd-pretty-diff: 2.0.3

From the quick glance, it looks that in new version they changed `CloudExecutable.synthesizer to be 
`export declare type Synthesizer = (aws: SdkProvider, config: Configuration) => Promise<cxapi.CloudAssembly>;`
but execProgram have type 
`export declare function execProgram(aws: SdkProvider, config: Configuration): Promise<ExecProgramResult>;` 
and it is trying to find manifest.missing on `ExecProgramResult` instead of assembly?

**Comment by joshweir** [comment]
Thanks for reporting this, I believe this should now be fixed with the above merged PR. I've bumped `cdk-pretty-diff` to `v2.1.0`. cheers

**Comment by sonicflare** [comment]
Thank you!
